name: CMake

on: [push, pull_request]

env:
  BUILD_TYPE: Release

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
    - name: Build software & execute tests
      run: |
        sudo apt-get install -y libgtest-dev libtbb-dev
        cmake -B ${{github.workspace}}/build -DCMAKE_BUILD_TYPE=${{env.BUILD_TYPE}}
        cmake --build ${{github.workspace}}/build --config ${{env.BUILD_TYPE}}
        cd ${{github.workspace}}/build
        ctest -C ${{env.BUILD_TYPE}}
