name: CMake

on: [push, pull_request]

jobs:
  build:
    runs-on: ubuntu-latest
    env:
      BUILD_DIRECTORY: ${{github.workspace}}/build
      BUILD_TYPE: Release
    steps:
    - name : Checkout
      uses: actions/checkout@v3
    - name: Build
      run: |
        sudo apt-get install -y libgtest-dev libtbb-dev
        cmake -B ${{env.BUILD_DIRECTORY}}  -DCMAKE_BUILD_TYPE=${{env.BUILD_TYPE}}
        cmake --build ${{env.BUILD_DIRECTORY}} --config ${{env.BUILD_TYPE}}
    - name: Test
      run: |
        cmake --build ${{env.BUILD_DIRECTORY}} --target check
